name: PHP-QA

on: [ push ]

jobs:
  lint-php:
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    with:
      PHP_VERSION: ${{ matrix.php }}
  tests-unit-php:
    strategy:
      matrix:
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
    with:
      PHP_VERSION: ${{ matrix.php }}
